version: "3.3"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: demo-database
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=pass1234
      - POSTGRESQL_DATABASE=medusa-my-medusa-store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./drfault-database.sql:/docker-entrypoint-initdb.d/drfault-database.sql

volumes:
  postgres_data:
